services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "credentials"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  credentials_storage:
    image: credentials_storage:0.1.0
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      CRED_SERVER_DATABASE_DSN: "postgresql://postgres:postgres@postgres:5432/credentials?sslmode=disable"
      CRED_SERVER_JWT_SECRET: "testJWT"
      CRED_SERVER_ENCRYPTION_SECRET: "test2"
      CRED_SERVER_LOCAL_STORAGE_LOCATION: "/tmp"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8090:8090"
